package com.GreenDao.model;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.GreenDao.model.FunctionDao;
import com.GreenDao.model.WuTypeDao;
import com.GreenDao.model.ChannelDao;
import com.GreenDao.model.RoomDao;
import com.GreenDao.model.WallUnitDao;
import com.GreenDao.model.MemoryDao;
import com.GreenDao.model.MemoryTypeDao;
import com.GreenDao.model.MemoryValueDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        FunctionDao.createTable(db, ifNotExists);
        WuTypeDao.createTable(db, ifNotExists);
        ChannelDao.createTable(db, ifNotExists);
        RoomDao.createTable(db, ifNotExists);
        WallUnitDao.createTable(db, ifNotExists);
        MemoryDao.createTable(db, ifNotExists);
        MemoryTypeDao.createTable(db, ifNotExists);
        MemoryValueDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        FunctionDao.dropTable(db, ifExists);
        WuTypeDao.dropTable(db, ifExists);
        ChannelDao.dropTable(db, ifExists);
        RoomDao.dropTable(db, ifExists);
        WallUnitDao.dropTable(db, ifExists);
        MemoryDao.dropTable(db, ifExists);
        MemoryTypeDao.dropTable(db, ifExists);
        MemoryValueDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(FunctionDao.class);
        registerDaoClass(WuTypeDao.class);
        registerDaoClass(ChannelDao.class);
        registerDaoClass(RoomDao.class);
        registerDaoClass(WallUnitDao.class);
        registerDaoClass(MemoryDao.class);
        registerDaoClass(MemoryTypeDao.class);
        registerDaoClass(MemoryValueDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
