package com.GreenDao.model;

import java.util.List;
import com.GreenDao.model.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WU_TYPE".
 */
public class WuType {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String descriptor;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient WuTypeDao myDao;

    private List<WallUnit> wallUnits;

    public WuType() {
    }

    public WuType(Long id) {
        this.id = id;
    }

    public WuType(Long id, String name, String descriptor) {
        this.id = id;
        this.name = name;
        this.descriptor = descriptor;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getWuTypeDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getDescriptor() {
        return descriptor;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescriptor(String descriptor) {
        this.descriptor = descriptor;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<WallUnit> getWallUnits() {
        if (wallUnits == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            WallUnitDao targetDao = daoSession.getWallUnitDao();
            List<WallUnit> wallUnitsNew = targetDao._queryWuType_WallUnits(id);
            synchronized (this) {
                if(wallUnits == null) {
                    wallUnits = wallUnitsNew;
                }
            }
        }
        return wallUnits;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetWallUnits() {
        wallUnits = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
